
from nicegui import app, context
import logging
from typing import Optional

logger = logging.getLogger("Language")

TRANSLATIONS = {
    "vi": {
        "language_changed": "Ngôn ngữ đã thay đổi",
        "language_change_success": "Ngôn ngữ đã thay đổi thành {new_lang}",
        "core_not_initialized": "Hệ thống lỗi: Core không được khởi tạo",
        "no_tabs_loaded": "Không có tab nào được tải, vui lòng kiểm tra cấu hình!",
        "invalid_session": "Phiên không hợp lệ",
        "dashboard_timeout": "Timeout khi render dashboard cho {username}: {error}",
        "dashboard_timeout_error": "Hết thời gian tải dashboard, vui lòng thử lại!",
        "dashboard_error": "Lỗi render dashboard cho {username}: {error}",
        "system_error": "Lỗi hệ thống: {error}",
        "auth_render_error": "Lỗi render giao diện auth: {error}",
        "username_label": "Tên người dùng",
        "username_hint": "Tối thiểu 3 ký tự, chỉ chứa chữ, số, dấu gạch dưới",
        "required_field": "Trường này là bắt buộc",
        "username_min_length": "Tối thiểu 3 ký tự",
        "username_pattern": "Chỉ chứa chữ, số, dấu gạch dưới",
        "password_label": "Mật khẩu",
        "password_hint": "Tối thiểu 8 ký tự",
        "password_min_length": "Tối thiểu 8 ký tự",
        "confirm_password_label": "Xác nhận mật khẩu",
        "bot_password_label": "Mật khẩu bot",
        "bot_password_required": "Mật khẩu bot là bắt buộc",
        "chat_tab": "Trò chuyện",
        "training_tab": "Huấn luyện",
        "download_tab": "Tải xuống",
        "welcome_label": "Chào mừng {username}",
        "logout_button": "Đăng xuất",
        "auth_title": "Đăng nhập/Đăng ký",
        "login_tab": "Đăng nhập",
        "register_tab": "Đăng ký",
        "login_button": "Đăng nhập",
        "register_button": "Đăng ký",
        "firestore_unavailable": "Firestore không khả dụng, ứng dụng đang chạy ở chế độ cục bộ!",
        "auth_timeout_error": "Hết thời gian tải giao diện, vui lòng thử lại!",
        "field_too_large": "Trường {key} quá dài!",
        "login_data_too_large": "Dữ liệu đăng nhập quá lớn!",
        "register_data_too_large": "Dữ liệu đăng ký quá lớn!",
        "login_timeout": "Timeout khi đăng nhập: {error}",
        "register_timeout": "Timeout khi đăng ký: {error}",
        "register_success": "Đăng ký thành công!",
        "register_error": "Đăng ký thất bại: {error}",
        "login_error": "Lỗi: {error}",
        "username_empty_error": "Tên người dùng không được để trống",
        "invalid_core_error": "Core không hợp lệ: Thiếu sqlite_handler",
        "invalid_client_state_error": "client_state phải là dictionary",
        "table_list_error": "Lỗi lấy danh sách bảng: {error}",
        "table_list_timeout": "Hết thời gian lấy danh sách bảng",
        "sync_table_error": "Lỗi lấy danh sách bảng đồng bộ: {error}",
        "no_chat_messages": "Cảnh báo: Không có tin nhắn trong cơ sở dữ liệu sau đồng bộ.",
        "no_qa_data": "Cảnh báo: Không có bản ghi Q&A trong cơ sở dữ liệu sau đồng bộ.",
        "tab_update_error": "Lỗi cập nhật tab {tab_name}: {error}",
        "tab_render_error": "Lỗi render tab {tab_name}: {error}",
        "no_tab_func": "Không thể cập nhật tab {tab_name}",
        "tabs_update_error": "Lỗi cập nhật các tab sau đồng bộ: {error}",
        "open_menu": "Mở menu",
        "language_select_label": "Chọn ngôn ngữ",
        "language_select_tooltip": "Chọn ngôn ngữ giao diện",
        "vietnamese": "Tiếng Việt",
        "english": "English",
        "update_avatar_label": "Cập nhật avatar",
        "upload_image_label": "Chọn và tải lên hình ảnh",
        "sync_status_error": "Lỗi trạng thái đồng bộ: {error}",
        "last_sync_label": "Lần đồng bộ cuối: {last_sync}",
        "never_synced": "Chưa đồng bộ",
        "sync_table_select_label": "Chọn bảng để đồng bộ",
        "sync_table_tooltip": "Chọn thêm bảng để đồng bộ cùng với các bảng được xác định bởi checkbox.",
        "protected_tables_only": "Chỉ đồng bộ bảng bảo vệ",
        "protected_tables_tooltip": "Nếu chọn, chỉ đồng bộ bảng bảo vệ và đặc biệt. Có thể kết hợp với các bảng trong dropdown.",
        "sync_from_firestore": "Đồng bộ từ Firestore",
        "sync_from_firestore_tooltip": "Đồng bộ dữ liệu từ Firestore về SQLite",
        "sync_to_firestore": "Đồng bộ lên Firestore",
        "sync_to_firestore_tooltip": "Đồng bộ dữ liệu từ SQLite lên Firestore",
        "logout_tooltip": "Đăng xuất",
        "header_render_error": "Lỗi render header: {error}",
        "header_timeout_error": "Hết thời gian render header",
        "header_recovery": "Header lỗi, đang khôi phục...",
        "sync_from_firestore_success": "Đồng bộ từ Firestore thành công: {records} bản ghi",
        "sync_from_firestore_timeout": "Timeout khi đồng bộ từ Firestore: {error}",
        "sync_from_firestore_error": "Lỗi đồng bộ từ Firestore: {error}",
        "sync_to_firestore_success": "Đồng bộ lên Firestore thành công: {records} bản ghi",
        "sync_to_firestore_timeout": "Timeout khi đồng bộ lên Firestore: {error}",
        "sync_to_firestore_error": "Lỗi đồng bộ lên Firestore: {error}",
        "sync_progress_label": "Đang đồng bộ {direction}...",
        "sync_timeout": "Timeout khi đồng bộ {direction}: {error}",
        "sync_error": "Lỗi đồng bộ {direction}: {error}",
        "avatar_size_error": "Kích thước file vượt quá {size} MB",
        "avatar_format_error": "Định dạng không được hỗ trợ. Cho phép: {formats}",
        "avatar_exists": "Avatar này đã tồn tại",
        "avatar_upload_success": "Upload avatar thành công",
        "avatar_upload_error": "Lỗi upload avatar: {error}",
        "header_update_error": "Lỗi cập nhật HeaderComponent: {error}",
        "id_label": "ID",
        "question_label": "Câu hỏi",
        "question_hint": "Nhập câu hỏi",
        "answer_label": "Câu trả lời",
        "answer_hint": "Nhập câu trả lời",
        "category_label": "Danh mục",
        "category_chat": "chat",
        "category_support": "support",
        "category_other": "other",
        "submit_button": "Gửi",
        "empty_session_token": "session_token rỗng, sử dụng field_name trực tiếp",
        "collect_field": "Thu thập {field_name}: {value}",
        "collect_field_error": "Không thể lấy dữ liệu cho trường {field_name}: {error}",
        "collected_form_data": "Dữ liệu form thu thập được: {data}",
        "fill_form_error": "Lỗi điền dữ liệu vào form: {error}",
        "cancel_edit_button": "Hủy chỉnh sửa",
        "delete_storage_key": "Xóa storage key: {key}",
        "form_reset_success": "Đã đặt lại form về trạng thái trống",
        "form_reset_error": "Lỗi đặt lại form: {error}",
        "submit_form_data": "Submit form với data: {data}",
        "form_processing": "Form đang được xử lý, bỏ qua submit",
        "form_data_too_large": "Dữ liệu form quá lớn, vượt quá 1MB",
        "question_empty": "Câu hỏi không được để trống",
        "answer_empty": "Câu trả lời không được để trống",
        "category_empty": "Danh mục không được để trống, dữ liệu nhận được: {data}",
        "submit_success": "Submit thành công: {message}",
        "save_qa_failed": "Lưu Q&A thất bại",
        "submit_failed": "Submit thất bại: {error}",
        "submit_form_error": "Lỗi submit form: {error}",
        "validation_error": "Không thể đánh giá validation {key}: {value}, lỗi: {error}",
        "invalid_core_error": "Lỗi: Đối tượng core không hợp lệ, thiếu sqlite_handler hoặc firestore_handler",
        "invalid_username_log": "username phải là chuỗi hợp lệ, nhận được: {type}",
        "invalid_username_error": "Lỗi: Username không hợp lệ",
        "ui_manager_set": "UIManager đã được gán cho DashboardLayout",
        "render_called": "render() được gọi với client_state: {state}",
        "invalid_client_state": "client_state không phải là dictionary",
        "invalid_client_state_error": "Lỗi: Trạng thái phiên không hợp lệ",
        "state_too_large": "Kích thước trạng thái vượt quá 1MB",
        "state_too_large_error": "Lỗi: Trạng thái phiên quá lớn",
        "no_client_state": "Không tìm thấy client_state, tạo mới",
        "load_client_state": "Tải client_state từ SQLite",
        "updated_tabs": "Đã cập nhật client_state tabs với: {tabs}",
        "tab_update_func": "Tab {tab_name} có update_func: {has_func}",
        "load_sync_status": "Tải trạng thái đồng bộ cho admin",
        "no_ui_manager": "UIManager chưa được gán cho DashboardLayout",
        "invalid_dashboard_config": "Lỗi: Cấu hình dashboard không hợp lệ",
        "welcome_dashboard": "Chào mừng đến với Dashboard",
        "no_tabs_configured": "Hiện tại không có tab nào được cấu hình. Vui lòng thêm các tab trong thư mục uiapp.",
        "no_tabs_default": "Hiển thị nội dung mặc định vì không có tab",
        "invalid_tab_name": "Tên tab không hợp lệ: {tab_name}",
        "invalid_tab_config": "Cấu hình tab không hợp lệ: {tab_name}",
        "invalid_render_func": "render_func của tab {tab_name} không hợp lệ hoặc không phải async",
        "load_tab_error": "Lỗi: Không thể tải tab {tab_name}",
        "render_tab_error": "Lỗi render tab {tab_name}: {error}",
        "details": "Chi tiết",
        "json_error": "Lỗi JSON khi render dashboard: {error}",
        "session_data_error": "Lỗi dữ liệu phiên: {error}",
        "display_dashboard_error": "Lỗi hiển thị dashboard: {error}",
        "invalid_tab_name_error": "Lỗi: Tên tab không hợp lệ",
        "invalid_client_state_session": "client_state không hợp lệ hoặc thiếu session_token",
        "invalid_session_state_error": "Lỗi: Trạng thái phiên không hợp lệ",
        "saved_selected_tab": "Lưu selected_tab={tab_name} vào client_states",
        "tab_change_timeout": "Hết thời gian xử lý thay đổi tab",
        "tab_change_timeout_log": "Timeout khi xử lý thay đổi tab",
        "json_tab_error": "Lỗi JSON khi lưu selected_tab: {error}",
        "tab_change_error": "Lỗi xử lý thay đổi tab: {error}",
        "sidebar_init": "SidebarComponent được khởi tạo với tabs: {tabs}, user={user}",
        "sidebar_render_start": "Đang render SidebarComponent với tabs={tabs}, user={user}",
        "sidebar_title": "Điều hướng",
        "rendering_tab_button": "Đang render nút cho tab {tab_name}",
        "select_tab_called": "select_tab được gọi cho tab {tab_name} bởi user {user}",
        "select_tab_skipped": "Bỏ qua select_tab vì loading=True cho tab {tab_name}",
        "saved_client_state": "{user}: Đã lưu client_state vào SQLite: selected_tab={tab}",
        "tab_changed": "{user}: Đã thay đổi tab qua sidebar: selected_tab={tab}, button_elements={buttons}",
        "button_created": "Đã tạo nút cho tab {tab_name}: {classes}",
        "invalid_on_select": "Lỗi: Hành động chọn tab không hợp lệ",
        "sidebar_render_error": "Lỗi render sidebar: {error}",
        "tab_select_error": "Lỗi chọn tab {tab_name}: {error}",
        "no_session_token": "session_token không tồn tại",
        "chat_ai_label": "Chat AI",
        "select_model_label": "Chọn mô hình AI",
        "select_mode_label": "Chế độ Chat",
        "message_input_label": "Tin nhắn",
        "upload_file_label": "Tải lên hình ảnh/file",
        "upload_button": "Tải lên",
        "send_button": "Gửi",
        "reset_button": "Xóa lịch sử",
        "no_messages_label": "Chưa có tin nhắn nào",
        "user_role_label": "Bạn",
        "ai_role_label": "AI",
        "image_not_found": "Hình ảnh không tồn tại: {file_url}",
        "wait_processing": "Vui lòng chờ xử lý",
        "invalid_mode_error": "Lỗi: Chế độ không hợp lệ",
        "mode_changed": "Chế độ: {mode}",
        "mode_change_error": "Lỗi đổi chế độ",
        "empty_message_error": "Vui lòng nhập tin nhắn!",
        "message_too_long_error": "Lỗi: Tin nhắn quá dài",
        "chat_ui_not_ready": "Lỗi: Giao diện chat chưa sẵn sàng",
        "invalid_chat_mode_error": "Lỗi: Chế độ chat không hợp lệ",
        "load_chat_ui_error": "Lỗi: Không thể tải giao diện chat",
        "chat_ui_load_error": "Lỗi tải giao diện chat",
        "chat_state_load_error": "Lỗi tải trạng thái chat",
        "send_message_error": "Lỗi gửi tin nhắn",
        "reset_history_error": "Lỗi xóa lịch sử chat",
        "update_messages_error": "Lỗi cập nhật tin nhắn",
        "no_qa_answer": "Không tìm thấy câu trả lời phù hợp",
        "processing_mode": "Xử lý trong chế độ {mode}",
        "grok_api_key_missing": "Lỗi: GROQ_API_KEY không được cấu hình",
        "grok_api_error": "Lỗi gọi API Grok",
        "unsupported_file_format": "Định dạng không được hỗ trợ. Cho phép: {formats}",
        "file_size_exceeded": "Kích thước file vượt quá {size} MB",
        "file_upload_success": "Đã gửi file {filename} thành công",
        "file_upload_error": "Lỗi upload file: {error}",
        "grok_vision_not_supported": "Grok miễn phí không hỗ trợ phân tích hình ảnh, nhưng bạn có thể gửi văn bản mô tả để được hỗ trợ.",
        "no_admin_access": "Chỉ admin có quyền truy cập tab training này",
        "render_training_error": "Đã xảy ra lỗi khi tải giao diện training.",
        "language_updated": "Đã cập nhật ngôn ngữ sang {lang}",
        "update_training_error": "Lỗi cập nhật giao diện training",
        "manage_qa_label": "Quản lý Q&A",
        "search_qa_label": "Tìm kiếm Q&A",
        "search_qa_placeholder": "Nhập từ khóa để tìm kiếm trong câu hỏi hoặc câu trả lời...",
        "question_label": "Câu hỏi",
        "answer_label": "Câu trả lời",
        "category_label": "Danh mục",
        "created_by_label": "Người tạo",
        "created_at_label": "Thời gian tạo",
        "edit_button": "Sửa",
        "delete_button": "Xóa",
        "save_qa_button": "Lưu Q&A",
        "import_json_button": "Nhập Q&A từ JSON",
        "export_qa_button": "Xuất Q&A sang JSON",
        "delete_all_qa_button": "Xóa toàn bộ Q&A",
        "no_qa_data_label": "⚠️ Chưa có dữ liệu Q&A",
        "no_qa_found": "Không tìm thấy Q&A phù hợp",
        "updated_qa_data": "Đã cập nhật dữ liệu Q&A",
        "loaded_qa_records": "Đã tải {count} bản ghi Q&A",
        "fetch_qa_error": "Lỗi lấy dữ liệu Q&A: {error}",
        "delete_qa_error": "Lỗi xóa Q&A: {error}",
        "export_qa_error": "Lỗi xuất Q&A: {error}",
        "import_json_error": "Lỗi nhập JSON Q&A: {error}",
        "import_file_error": "Lỗi nhập Q&A từ file: {error}",
        "save_qa_error": "Lỗi lưu Q&A: {error}",
        "invalid_json_list": "JSON phải là danh sách",
        "no_valid_qa": "Không có bản ghi Q&A hợp lệ",
        "file_too_large": "File quá lớn",
        "unsupported_file_format": "Chỉ chấp nhận JSON hoặc CSV",
        "duplicate_qa": "Q&A này đã tồn tại, bỏ qua để tránh duplicate",
        "qa_too_large": "Dữ liệu Q&A quá lớn",
        "invalid_session": "Lỗi: Phiên đăng nhập không hợp lệ",
        "state_too_large": "Lỗi: Trạng thái phiên quá lớn",
        "save_state_error": "Lỗi lưu trạng thái",
        "edit_qa_filled": "Đã điền dữ liệu để chỉnh sửa Q&A",
        "edit_qa_error": "Lỗi điền dữ liệu chỉnh sửa Q&A: {error}",
        "cancel_edit_qa": "Đã hủy chỉnh sửa Q&A",
        "cancel_edit_error": "Lỗi hủy chỉnh sửa Q&A: {error}",
        "confirm_delete_qa": "Bạn có chắc muốn xóa {count} Q&A{search}?",
        "deleted_qa": "Đã xóa Q&A {id}",
        "deleted_qa_batch": "Đã xóa {count} Q&A{search}",
        "cancel_delete": "Hủy xóa",
        "search_results": "Tìm thấy {count} kết quả",
        "fts_not_ready": "Sử dụng tìm kiếm cơ bản (FTS chưa sẵn sàng)",
        "too_many_results": "Tìm thấy nhiều kết quả ({count}), chỉ hiển thị trang {page}",
        "header_update_error": "Lỗi cập nhật HeaderComponent: {error}",
        "welcome_label": "Chào {username}",
        "open_menu": "Mở menu",
        "language_select_label": "Chọn Ngôn ngữ",
        "language_select_tooltip": "Chọn ngôn ngữ giao diện",
        "vietnamese": "Tiếng Việt",
        "english": "Tiếng Anh",
        "invalid_language": "Ngôn ngữ không hợp lệ: {new_lang}",
        "language_change_error": "Lỗi thay đổi ngôn ngữ: {error_msg}",
        "components_update_error": "Lỗi cập nhật các thành phần sau khi thay đổi ngôn ngữ: {error_msg}",
        "tab_update_error": "Lỗi cập nhật tab {tab_name}: {error_msg}"
    
    },
    "en": {
        # ... các chuỗi khác ...
        "no_admin_access": "Only admins can access this training tab",
        "render_training_error": "An error occurred while loading the training interface.",

        
        "language_changed": "Language changed",
        "language_change_success": "Language changed to {new_lang}",
        "core_not_initialized": "System error: Core not initialized",
        "no_tabs_loaded": "No tabs loaded, please check tab configuration!",
        "invalid_session": "Invalid session",
        "dashboard_timeout": "Timeout rendering dashboard for {username}: {error}",
        "dashboard_timeout_error": "Dashboard timeout error",
        "dashboard_error": "Error rendering dashboard for {username}: {error}",
        "system_error": "System error: {error}",
        "auth_render_error": "Error rendering auth interface: {error}",
        "username_label": "Username",
        "username_hint": "Minimum 3 characters, letters, numbers, underscore only",
        "required_field": "This field is required",
        "username_min_length": "Minimum 3 characters",
        "username_pattern": "Only letters, numbers, and underscore allowed",
        "password_label": "Password",
        "password_hint": "Minimum 8 characters",
        "password_min_length": "Minimum 8 characters",
        "confirm_password_label": "Confirm Password",
        "bot_password_label": "Bot Password",
        "bot_password_required": "Bot password is required",
        "chat_tab": "Chat",
        "training_tab": "Training",
        "download_tab": "Download",
        "welcome_label": "Welcome {username}",
        "logout_button": "Logout",
        "auth_title": "Login/Register",
        "login_tab": "Login",
        "register_tab": "Register",
        "login_button": "Login",
        "register_button": "Register",
        "firestore_unavailable": "Firestore unavailable, running in local mode!",
        "auth_timeout_error": "Timeout loading auth interface, please try again!",
        "field_too_large": "Field {key} is too large!",
        "login_data_too_large": "Login data too large!",
        "register_data_too_large": "Register data too large!",
        "login_timeout": "Timeout during login: {error}",
        "register_timeout": "Timeout during registration: {error}",
        "register_success": "Registration successful!",
        "register_error": "Registration failed: {error}",
        "login_error": "Error: {error}",
        "username_empty_error": "Username cannot be empty",
        "invalid_core_error": "Invalid core: Missing sqlite_handler",
        "invalid_client_state_error": "client_state must be a dictionary",
        "table_list_error": "Error fetching table list: {error}",
        "table_list_timeout": "Timeout fetching table list",
        "sync_table_error": "Error fetching sync tables: {error}",
        "no_chat_messages": "Warning: No chat messages in database after sync.",
        "no_qa_data": "Warning: No Q&A records in database after sync.",
        "tab_update_error": "Error updating tab {tab_name}: {error}",
        "tab_render_error": "Error rendering tab {tab_name}: {error}",
        "no_tab_func": "Cannot update tab {tab_name}",
        "tabs_update_error": "Error updating tabs after sync: {error}",
        "open_menu": "Open menu",
        "language_select_label": "Select Language",
        "language_select_tooltip": "Choose interface language",
        "vietnamese": "Vietnamese",
        "english": "English",
        "update_avatar_label": "Update Avatar",
        "upload_image_label": "Choose and upload image",
        "sync_status_error": "Sync status error: {error}",
        "last_sync_label": "Last sync: {last_sync}",
        "never_synced": "Never synced",
        "sync_table_select_label": "Select tables to sync",
        "sync_table_tooltip": "Select additional tables to sync with protected/special tables",
        "protected_tables_only": "Sync only protected tables",
        "protected_tables_tooltip": "If checked, sync only protected and special tables. Can combine with dropdown tables.",
        "sync_from_firestore": "Sync from Firestore",
        "sync_from_firestore_tooltip": "Sync data from Firestore to SQLite",
        "sync_to_firestore": "Sync to Firestore",
        "sync_to_firestore_tooltip": "Sync data from SQLite to Firestore",
        "logout_tooltip": "Log out",
        "header_render_error": "Error rendering header: {error}",
        "header_timeout_error": "Timeout rendering header",
        "header_recovery": "Header error, recovering...",
        "sync_from_firestore_success": "Synced from Firestore: {records} records",
        "sync_from_firestore_timeout": "Timeout syncing from Firestore: {error}",
        "sync_from_firestore_error": "Error syncing from Firestore: {error}",
        "sync_to_firestore_success": "Synced to Firestore: {records} records",
        "sync_to_firestore_timeout": "Timeout syncing to Firestore: {error}",
        "sync_to_firestore_error": "Error syncing to Firestore: {error}",
        "sync_progress_label": "Syncing {direction}...",
        "sync_timeout": "Timeout syncing {direction}: {error}",
        "sync_error": "Error syncing {direction}: {error}",
        "avatar_size_error": "File size exceeds {size} MB",
        "avatar_format_error": "Unsupported format. Allowed: {formats}",
        "avatar_exists": "This avatar already exists",
        "avatar_upload_success": "Avatar uploaded successfully",
        "avatar_upload_error": "Error uploading avatar: {error}",
        "header_update_error": "Error updating HeaderComponent: {error}",
        "id_label": "ID",
        "question_label": "Question",
        "question_hint": "Enter question",
        "answer_label": "Answer",
        "answer_hint": "Enter answer",
        "category_label": "Category",
        "category_chat": "chat",
        "category_support": "support",
        "category_other": "other",
        "submit_button": "Submit",
        "empty_session_token": "session_token is empty, using field_name directly",
        "collect_field": "Collected {field_name}: {value}",
        "collect_field_error": "Cannot collect data for field {field_name}: {error}",
        "collected_form_data": "Collected form data: {data}",
        "fill_form_error": "Error filling form: {error}",
        "cancel_edit_button": "Cancel Edit",
        "delete_storage_key": "Deleting storage key: {key}",
        "form_reset_success": "Form reset to empty state",
        "form_reset_error": "Error resetting form: {error}",
        "submit_form_data": "Submitting form with data: {data}",
        "form_processing": "Form is being processed, ignoring submit",
        "form_data_too_large": "Form data too large, exceeds 1MB",
        "question_empty": "Question cannot be empty",
        "answer_empty": "Answer cannot be empty",
        "category_empty": "Category cannot be empty, received data: {data}",
        "submit_success": "Submit successful: {message}",
        "save_qa_failed": "Failed to save Q&A",
        "submit_failed": "Submit failed: {error}",
        "submit_form_error": "Error submitting form: {error}",
        "validation_error": "Cannot evaluate validation {key}: {value}, error: {error}",
        "invalid_core_error": "Error: Invalid core object, missing sqlite_handler or firestore_handler",
        "invalid_username_log": "username must be a valid string, received: {type}",
        "invalid_username_error": "Error: Invalid username",
        "ui_manager_set": "UIManager assigned to DashboardLayout",
        "render_called": "render() called with client_state: {state}",
        "invalid_client_state": "client_state is not a dictionary",
        "invalid_client_state_error": "Error: Invalid session state",
        "state_too_large": "State size exceeds 1MB",
        "state_too_large_error": "Error: Session state too large",
        "no_client_state": "No client_state found, creating new",
        "load_client_state": "Loaded client_state from SQLite",
        "updated_tabs": "Updated client_state tabs with: {tabs}",
        "tab_update_func": "Tab {tab_name} has update_func: {has_func}",
        "load_sync_status": "Loaded sync status for admin",
        "no_ui_manager": "UIManager not assigned to DashboardLayout",
        "invalid_dashboard_config": "Error: Invalid dashboard configuration",
        "welcome_dashboard": "Welcome to Dashboard",
        "no_tabs_configured": "No tabs configured. Please add tabs in the uiapp directory.",
        "no_tabs_default": "Displayed default content due to no tabs",
        "invalid_tab_name": "Invalid tab name: {tab_name}",
        "invalid_tab_config": "Invalid tab configuration: {tab_name}",
        "invalid_render_func": "render_func for tab {tab_name} is invalid or not async",
        "load_tab_error": "Error: Cannot load tab {tab_name}",
        "render_tab_error": "Error rendering tab {tab_name}: {error}",
        "details": "Details",
        "json_error": "JSON error rendering dashboard: {error}",
        "session_data_error": "Session data error: {error}",
        "display_dashboard_error": "Error displaying dashboard: {error}",
        "invalid_tab_name_error": "Error: Invalid tab name",
        "invalid_client_state_session": "client_state is invalid or missing session_token",
        "invalid_session_state_error": "Error: Invalid session state",
        "saved_selected_tab": "Saved selected_tab={tab_name} to client_states",
        "tab_change_timeout": "Timeout processing tab change",
        "tab_change_timeout_log": "Timeout processing tab change",
        "json_tab_error": "JSON error saving selected_tab: {error}",
        "tab_change_error": "Error processing tab change: {error}",
        "sidebar_init": "SidebarComponent initialized with tabs: {tabs}, user={user}",
        "sidebar_render_start": "Rendering SidebarComponent with tabs={tabs}, user={user}",
        "sidebar_title": "Navigation",
        "rendering_tab_button": "Rendering button for tab {tab_name}",
        "select_tab_called": "select_tab called for tab {tab_name} by user {user}",
        "select_tab_skipped": "select_tab skipped due to loading=True for tab {tab_name}",
        "saved_client_state": "{user}: Saved client_state to SQLite: selected_tab={tab}",
        "tab_changed": "{user}: Tab changed via sidebar: selected_tab={tab}, button_elements={buttons}",
        "button_created": "Button created for tab {tab_name}: {classes}",
        "invalid_on_select": "Error: Invalid tab selection action",
        "sidebar_render_error": "Error rendering sidebar: {error}",
        "tab_select_error": "Error selecting tab {tab_name}: {error}",
        "no_session_token": "session_token does not exist",
        "chat_ai_label": "Chat AI",
        "select_model_label": "Select AI Model",
        "select_mode_label": "Chat Mode",
        "message_input_label": "Message",
        "upload_file_label": "Upload Image/File",
        "upload_button": "Upload",
        "send_button": "Send",
        "reset_button": "Clear History",
        "no_messages_label": "No messages yet",
        "user_role_label": "You",
        "ai_role_label": "AI",
        "image_not_found": "Image not found: {file_url}",
        "wait_processing": "Please wait while processing",
        "invalid_mode_error": "Error: Invalid mode",
        "mode_changed": "Mode: {mode}",
        "mode_change_error": "Error changing mode",
        "empty_message_error": "Please enter a message!",
        "message_too_long_error": "Error: Message too long",
        "chat_ui_not_ready": "Error: Chat interface not ready",
        "invalid_chat_mode_error": "Error: Invalid chat mode",
        "load_chat_ui_error": "Error: Cannot load chat interface",
        "chat_ui_load_error": "Error loading chat interface",
        "chat_state_load_error": "Error loading chat state",
        "send_message_error": "Error sending message",
        "reset_history_error": "Error clearing chat history",
        "update_messages_error": "Error updating messages",
        "no_qa_answer": "No matching answer found",
        "processing_mode": "Processing in {mode} mode",
        "grok_api_key_missing": "Error: GROQ_API_KEY not configured",
        "grok_api_error": "Error calling Grok API",
        "unsupported_file_format": "Unsupported format. Allowed: {formats}",
        "file_size_exceeded": "File size exceeds {size} MB",
        "file_upload_success": "File {filename} uploaded successfully",
        "file_upload_error": "Error uploading file: {error}",
        "grok_vision_not_supported": "Free Grok does not support image analysis, but you can send a text description for assistance.",
        "language_updated": "Language updated to {lang}",
        "update_training_error": "Error updating training UI",
        "manage_qa_label": "Manage Q&A",
        "search_qa_label": "Search Q&A",
        "search_qa_placeholder": "Enter keyword to search in questions or answers...",
        "question_label": "Question",
        "answer_label": "Answer",
        "category_label": "Category",
        "created_by_label": "Created by",
        "created_at_label": "Created at",
        "edit_button": "Edit",
        "delete_button": "Delete",
        "save_qa_button": "Save Q&A",
        "import_json_button": "Import Q&A from JSON",
        "export_qa_button": "Export Q&A to JSON",
        "delete_all_qa_button": "Delete All Q&A",
        "no_qa_data_label": "⚠️ No Q&A data available",
        "no_qa_found": "No matching Q&A found",
        "updated_qa_data": "Updated Q&A data",
        "loaded_qa_records": "Loaded {count} Q&A records",
        "fetch_qa_error": "Error fetching Q&A data: {error}",
        "delete_qa_error": "Error deleting Q&A: {error}",
        "export_qa_error": "Error exporting Q&A: {error}",
        "import_json_error": "Error importing JSON Q&A: {error}",
        "import_file_error": "Error importing Q&A from file: {error}",
        "save_qa_error": "Error saving Q&A: {error}",
        "invalid_json_list": "JSON must be a list",
        "no_valid_qa": "No valid Q&A records",
        "file_too_large": "File too large",
        "unsupported_file_format": "Only JSON or CSV accepted",
        "duplicate_qa": "Q&A already exists, skipped to avoid duplicate",
        "qa_too_large": "Q&A data too large",
        "invalid_session": "Error: Invalid session",
        "state_too_large": "Error: Session state too large",
        "save_state_error": "Error saving state",
        "edit_qa_filled": "Filled data for editing Q&A",
        "edit_qa_error": "Error filling edit Q&A data: {error}",
        "cancel_edit_qa": "Cancelled Q&A edit",
        "cancel_edit_error": "Error cancelling Q&A edit: {error}",
        "confirm_delete_qa": "Are you sure you want to delete {count} Q&A{search}?",
        "deleted_qa": "Deleted Q&A {id}",
        "deleted_qa_batch": "Deleted {count} Q&A{search}",
        "cancel_delete": "Delete cancelled",
        "search_results": "Found {count} results",
        "fts_not_ready": "Using basic search (FTS not ready)",
        "too_many_results": "Found many results ({count}), showing page {page}",
        "header_update_error": "Error updating HeaderComponent: {error}",
        "welcome_label": "Welcome {username}",
        "open_menu": "Open menu",
        "language_select_label": "Select Language",
        "language_select_tooltip": "Choose interface language",
        "vietnamese": "Vietnamese",
        "english": "English",
        "invalid_language": "Invalid language: {new_lang}",
        "language_change_error": "Error changing language: {error_msg}",
        "components_update_error": "Error updating components after language change: {error_msg}",
        "tab_update_error": "Error updating tab {tab_name}: {error_msg}"
    
    }
}

def get_text(lang: str, key: str, default: Optional[str] = None, **kwargs) -> str:
    """
    Lấy chuỗi dịch theo ngôn ngữ và key.

    Args:
        lang: Ngôn ngữ ('vi' hoặc 'en')
        key: Key của chuỗi cần dịch
        default: Giá trị mặc định nếu không tìm thấy key
        **kwargs: Tham số để định dạng chuỗi

    Returns:
        Chuỗi đã dịch hoặc giá trị mặc định
    """
    lang = lang if lang in TRANSLATIONS else "vi"
    translation = TRANSLATIONS.get(lang, {}).get(key, default or key)
    if kwargs:
        try:
            return translation.format(**kwargs)
        except (KeyError, ValueError):
            return translation
    return translation